### ISSUE TITLE
You didn't properly merge branches

### ISSUE THREAD

**Issue by CircuitSacul** [stroupbslayen/discord-pretty-help#1]
If you look in the actual code, it's the same code repeated twice. One for "head" and one for "7d35efce2664295eae316bfbf3c2f3e7509fa666".

I managed to fix it for myself but I just thought that you might want to fix it as well. Also, your code crashes when it is used for dm because the bot can't remove user reactions.

**Comment by stroupbslayen** [comment]
Thanks for letting me know! The branch I was trying to merge addressed the dm issue so that should be good now too.

**Comment by CircuitSacul** [comment]
Yes, thanks for fixing that. Also, I made a slight modification on the file so that it included page number on the help message, as well as a "stop" button that would allow the user to delete the message. Is it possible for you to add this to your version as well?

**Comment by stroupbslayen** [comment]
No problem 
![image](https://user-images.githubusercontent.com/29642143/86613129-033b2a80-bf66-11ea-823b-39c560c0f024.png)

**Comment by CircuitSacul** [comment]
That looks great. I just wanted to let you know that if you do `help <category>`, it shows `page:1/2` even though it is just listing commands for that category.
![Screen Shot 2020-07-06 at 12 35 13 PM](https://user-images.githubusercontent.com/55721663/86617365-1b6e7200-bf85-11ea-85ed-d9ff92c65503.png)

I added `print(page.title)` after line 241 in your code, and got the following output when I ran `help Settings` (Settings is a category):
```
Commands:
Settings
```

It seems that `self.paginator.pages` is always 2, even when just running on a category. This makes it so that it shows `page:1/2` even when `bot_help` is false.

For further debugging, I forced `bot_help` to true, and these are what I got:
![Screen Shot 2020-07-06 at 12 48 12 PM](https://user-images.githubusercontent.com/55721663/86618442-ebc06980-bf86-11ea-97b1-5653d131acf3.png)
![Screen Shot 2020-07-06 at 12 48 03 PM](https://user-images.githubusercontent.com/55721663/86618464-f67afe80-bf86-11ea-9676-0ca346f0a776.png)

When I added the page numbers myself, my solution to this problem was to only display page numbers if `bot_help` was true, because that really is the only time page numbers need to be displayed.

Sorry if I've been bothering you too much.

**Comment by stroupbslayen** [comment]
No problem man, it might be faster to just add me on discord too. 

Fixed the issue though, and noticed that it would up the cog description as the title if it had one so that should be good too.
![image](https://user-images.githubusercontent.com/29642143/86629163-d7c53980-bf7f-11ea-9d9a-85f9e38c99fb.png)
