### ISSUE TITLE
Hide Cogs/Categories

### ISSUE THREAD

**Issue by ClearlyRubix** [stroupbslayen/discord-pretty-help#10]
I have a cog with hidden, owner-only debugging commands. This is not a category users should be worried about so I would like to hide it. I didn't see anything in the docs so help would be greatly appreciated.

**Comment by stroupbslayen** [comment]
Hi,

Are you suggesting another option?
`help = PrettyHelp(hidden=['cog1','cog2']`

Or is the category showing up but is empty?

**Comment by CircuitSacul** [comment]
I've experienced this with the index, where I have cogs that have no commands but it shows up on the categories page.

**Comment by stroupbslayen** [comment]
Ok, I'll look into it.

**Comment by stroupbslayen** [comment]
The latest version should address this issue.
