### ISSUE TITLE
Reaction not working

### ISSUE THREAD

**Issue by Lost1419** [stroupbslayen/discord-pretty-help#12]
When you add your own custom emoji the changing of page doesn't work.
The removing of reactions also doesn't work.

**Comment by stroupbslayen** [comment]
Custom emojis are in this format `:emoji:768927487823970365`
Sounds like maybe you used what discord gave you? `<:xbox:768927487823970365>`
I've added a quick match to pull the valid format from the initial emojis just to make it less confusing. Update your version and see if it works now.
