### ISSUE TITLE
Feature: Raise BotMissingPermissions if the bot doesn't have needed perms

### ISSUE THREAD

**Issue by CircuitSacul** [stroupbslayen/discord-pretty-help#13]
I don't know how hard this would be, but it would be nice if you added a check that looks at the bot permissions for that channel. In order for the help command to work, the bot needs the following perms:
 - read_message_history
 - add_reactions
 - embed_links

If the bot doesn't have to first two, it raises a "forbidden" error *after* it has sent the message. These errors would be easier to handle if it instead checked it's perms when starting, and raised a `BotMissingPerms` error if it's missing permissions.

**Comment by stroupbslayen** [comment]
Merged and updated, thanks!
