### ISSUE TITLE
Command raised an exception: NameError 'owners' is not defined 

### ISSUE THREAD

**Issue by Abood025** [stroupbslayen/discord-pretty-help#15]
Idk y i got this error

**Comment by stroupbslayen** [comment]
You gotta provide some useful information dude

**Comment by Abood025** [comment]
in the console I only get that error 
nothing more written
and also
When i type ?help it gives error
but
when i write ?help ping it shows info about command
i guess it cant add reactions?
tho it has admin perms

**Comment by stroupbslayen** [comment]
Can you please provide the full traceback?

**Comment by Abood025** [comment]
![C927E205-AF29-49B2-9A36-30BD0914F154](https://user-images.githubusercontent.com/68436379/97348708-f7be9700-18a7-11eb-83e2-0f568588b829.jpeg)

**Comment by stroupbslayen** [comment]
Still not really helpful. It looks like you have a cog/command that's got a `NameError` in it and isn't related to the help menu.
