### ISSUE TITLE
How to hide a category or command?

### ISSUE THREAD

**Issue by ATOMICMAN007** [stroupbslayen/discord-pretty-help#17]
I did `hidden=True` in some commands, they still showed up in `PrettyHelp` embed. Also **aliases** don't show up as well as the **discription** appears on the right side of command name which makes it a bit uncomfortable. Thanks for this module, you people really really did a great job making it but a little improvements here and there are needed. 😊

**Comment by stroupbslayen** [comment]
The latest version should address a lot of this. Thanks for your input!
