### ISSUE TITLE
ModuleNotFoundError: No module named 'pretty_help'

### ISSUE THREAD

**Issue by MrDragonBoi** [stroupbslayen/discord-pretty-help#18]
Traceback:
  File "bot.py", line 4, in <module>
    from pretty_help import PrettyHelp
ModuleNotFoundError: No module named 'pretty_help'
All I did, was what the readme said :/

Why is this?

**Comment by stroupbslayen** [comment]
Is it in your installed pip packages?

**Comment by MrDragonBoi** [comment]
Yes From: stroupbslayenSent: 30 November 2020 16:05To: stroupbslayen/discord-pretty-helpCc: Leon Peter Keates; AuthorSubject: Re: [stroupbslayen/discord-pretty-help] ModuleNotFoundError: No module named 'pretty_help' (#18) Is it in your installed pip packages?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by stroupbslayen** [comment]
This doesn't really help...

**Comment by MrDragonBoi** [comment]
I replied via Email, which was a bad idea. However, it is installed, its probably the version on my host (Python 3.8.0?

**Comment by stroupbslayen** [comment]
I'm not sure that you do have it installed, I just tried it with 3.8 and it's works as expected. The error you're getting indicates it can't find it, so maybe you installed it globally instead of in your env or visa versa? When you do `pip list` it shows as an installed package?
