### ISSUE TITLE
"End Note" Only shows on "No Category"

### ISSUE THREAD

**Issue by CircuitSacul** [stroupbslayen/discord-pretty-help#2]
When you get the endnote, the message that is usually `Type <prefix> help command for more info on a command.
You can also type beta help category for more info on a category.`, It only shows on the "No Category" category. This is mostly a problem for me because the categories are sorted alphabetically, and sometimes "No Category" is 2nd or 3rd, which (imo) looks weird. This might not be a problem necessarily, but I would recommend showing the endnote on every page.

**Comment by stroupbslayen** [comment]
No problem, added it to the footer for every page.
