### ISSUE TITLE
@bot.command(description=<string>) does not change the description of "None" for the command

### ISSUE THREAD

**Issue by seamuskills** [stroupbslayen/discord-pretty-help#20]
I am trying to get the description of commands to work. an example is this command:

bot.command(description="puts 3 ` around your text")
async def codetext(ctx,*,code):
	await ctx.send(ctx.author.name+":\n```\n"+code+"\n```")
	await ctx.message.delete()

but the help command says None where the description should be.

thanks for reading have a nice day.

**Comment by seamuskills** [comment]
if you need the full code, the repl link is here: https://repl.it/@SeamusDonahue/utility-bot#main.py and the github here: https://github.com/seamuskills/utility-bot/

**Comment by stroupbslayen** [comment]
Hi, use the `help` kwarg or add the text as the command doc:

```py
@bot.command(help="puts 3 ` around your text")
async def codetext(ctx,*,code):
  await ctx.send(ctx.author.name+":\n\n"+code+"\n")
  await ctx.message.delete()
```
or

```py
@bot.command()
async def codetext(ctx,*,code):
  """puts 3 ` around your text"""
  await ctx.send(ctx.author.name+":\n\n"+code+"\n")
  await ctx.message.delete()```

**Comment by seamuskills** [comment]
Thanks that solved my issue
