### ISSUE TITLE
How to add description and how to make the index start with (1) and not (2)

### ISSUE THREAD

**Issue by Nxuz** [stroupbslayen/discord-pretty-help#21]
![Desktop Screenshot 2021 01 18 - 12 07 09 87](https://user-images.githubusercontent.com/75790795/104880552-c5dc3e80-5985-11eb-8bc9-c299ff308b9f.png)
![Desktop Screenshot 2021 01 18 - 12 07 21 47](https://user-images.githubusercontent.com/75790795/104880558-c7a60200-5985-11eb-83c3-3109286b94c3.png)

**Comment by stroupbslayen** [comment]
For the "No Description" on commands see this issue #20 
You can add a description to your Cogs in a similar way with docstrings.

For the page indexes, the index page is the first page in the menu and the `2) Fun` is to reference what page it's on. Right now the only way to make your `Fun` cog the first page would be to turn off the index page.
