### ISSUE TITLE
[Suggestion] Multiple Cog Pages 

### ISSUE THREAD

**Issue by Motzumoto** [stroupbslayen/discord-pretty-help#22]
Allow for multiple pages if a category has more than able to be displayed commands. For instance, one of my cogs has over 50 commands, when sending the help command for that cog it only displays every command it can, which isnt very many, so that causes a lot of commands to be cut off and not shown at all.

**Comment by Motzumoto** [comment]
@stroupbslayen Will this enhancement be added?

**Comment by stroupbslayen** [comment]
Yes, I've just been swamped with other stuff the last couple weeks, hopefully I'll get to it tomorrow.

**Comment by Motzumoto** [comment]
> Yes, I've just been swamped with other stuff the last couple weeks, hopefully I'll get to it tomorrow.

Alright awesome, take your time

**Comment by stroupbslayen** [comment]
Added proper pagination. Thanks for bringing this up 👍
