### ISSUE TITLE
Hability to edit the footer

### ISSUE THREAD

**Issue by Mara-Li** [stroupbslayen/discord-pretty-help#28]
So, it's me again !
It will be really helpful to have the possibility to edit the footnote. Like : I'm french, and I want to translate it in french.
Maybe it's already possible, so : how ? 
If it isn't possible, maybe add the possibility like the other option (nav, color...) ?

Thank you !

**Comment by stroupbslayen** [comment]
I thought I already had this included but I guess not. You can now set the embed footer using the `ending_note` kwarg.
