### ISSUE TITLE
NotFound error if help message was deleted

### ISSUE THREAD

**Issue by CircuitSacul** [stroupbslayen/discord-pretty-help#3]
If you call `help`, then delete the help message manually, the function will raise an error when it tries to remove the reactions. This should be an easy fix, just except `discord.ext.commands.errors.CommandInvokeError`

Here is the full error message:
```
<class 'discord.ext.commands.errors.CommandInvokeError'>:
 Command raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message
```

I'm pretty sure this is the last issue I'll find.

**Comment by stroupbslayen** [comment]
Just revised to eat errors after timeout, thanks!
