### ISSUE TITLE
Ending note edit : Get prefix

### ISSUE THREAD

**Issue by Mara-Li** [stroupbslayen/discord-pretty-help#30]
How can I get the prefix to add it on my ending note ?

**Comment by PlasmaAsDev** [comment]
Hi! You can assign the prefix as a string to a variable like `prefix = "!"` and format the ending note like this: `ending_note=f"{prefix}(command)`

**Comment by Mara-Li** [comment]
Yeah, but my prefix is in a database, so I need to check it before... I try a lot of things, but everytime, my command "get_prefix" return a strange things like `<bound method BotBase.get_prefix of <discord.ext.commands.bot.Bot object at 0x0000027D418BF100>>` or `<function getprefix at 0x000001B970F9BDC0>`. My getprefix is :  
```python
def getprefix(bot, message):
	db = sqlite3.connect("owlly.db", timeout=3000)
	c = db.cursor()
	prefix = "SELECT prefix FROM SERVEUR WHERE idS = ?"
	c.execute(prefix, (int(message.guild.id), ))
	prefix = c.fetchone()
	if prefix is None:
		prefix = "?"
		sql = "INSERT INTO SERVEUR (prefix, idS) VALUES (?,?)"
		var = ("?", message.guild.id)
		c.execute(sql, var)
		db.commit()
	else:
		prefix = prefix[0]
	c.close()
	db.close()
	return prefix
```
If you have an idea !

**Comment by stroupbslayen** [comment]
Thanks for bringing this up, I just added a way to create more advanced ending notes. You're now able to access the command context using `ctx` and PrettyHelp instance using `help` in your formatted strings.

```py
# custom ending note using the command context and help command formatters
ending_note = "The ending not from {ctx.bot.user.name}\nFor command {help.clean_prefix}{help.invoked_with}"

bot.help_command = PrettyHelp(ending_note=ending_note)
```

**Comment by Mara-Li** [comment]
Whow ! Thanks you so much, you're super great :>
