### ISSUE TITLE
[Feature Request] Add optional "show required permissions" field to command help

### ISSUE THREAD

**Issue by CircuitSacul** [stroupbslayen/discord-pretty-help#32]
It would be cool if there was an option on PrettyHelp that, when enabled, would show the permission required for the user to run the command. This isn't necessarily helpful for users seeing what commands *they* can run, but is very useful to server admins who want to see what commands *others* can run.

I would be willing to implement this if you think this is worthwhile.

**Comment by Music-Dude** [comment]
I think this would be useful too. Maybe a toggleable feature to show only commands the user can access or all commands (as well as NSFW commands, which only show in NSFW channels)

**Comment by CircuitSacul** [comment]
What if you have a command called "general" as well as a cog called "General"?

**Comment by anselal** [comment]
The help command already shows only the commands the user calling the help can access.
