### ISSUE TITLE
Help error? i dont know what to title

### ISSUE THREAD

**Issue by ritik0ranjan** [stroupbslayen/discord-pretty-help#33]
I think something wrong with this code.. help command is not working. 
```
Ignoring exception in command help:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/help.py", line 848, in command_callback
    return await self.send_bot_help(mapping)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pretty_help/pretty_help.py", line 320, in send_bot_help
    mapping[cmd.cog].append(cmd)
KeyError: <cogs.misc.rtfm.tools._Tools object at 0x7f2ffb0d0f70>
```

**Comment by stroupbslayen** [comment]
What does your cog look like?

**Comment by ritik0ranjan** [comment]
A folder many folders in one single folder named, `cog`
![Screenshot 2021-04-12 08:05:04](https://user-images.githubusercontent.com/37435729/114343123-e0841500-9b7a-11eb-88e5-1e7b883ae8c9.png)
![Screenshot 2021-04-12 08:07:36](https://user-images.githubusercontent.com/37435729/114343177-00b3d400-9b7b-11eb-8543-54e4930c959c.png)

**Comment by ritik0ranjan** [comment]
`[prefix]help` is only not working, `[prefix]help [cmd]` is working fine.

**Comment by stroupbslayen** [comment]
Ok, this error is coming from `cogs.misc.rtfm.tools._Tools` so what does that cog look like?

**Comment by stroupbslayen** [comment]
Something in your setup is causing the issue, without knowing how you've set it up there's not really anything I can do. I looks like somehow the bot isn't seeing that cog, but it's seeing the commands in it.

**Comment by ritik0ranjan** [comment]
Thing is, I deleted that file, and merge the commands with other one, but the issue didn't fixed. Now, `discord-pretty-help` (it, your code, your work) is giving `KeyError` from different `cog`. I think your code won't work if we make nested cogs (folders into folder). I am saying so, cause earlier when I was having the less commands all the `cog`(s) were in one folder, and it was working fine. But after making more it's no longer working. To be honest, I like your work.

**Comment by stroupbslayen** [comment]
I thought that might be the issue too and tried to recreate the issue, but even when I go many directories deep it still works for me. I even made it on repl.it to see if maybe that was causing it, still worked for me. Sorry man, I want to solve your issue but I can't recreate it.

**Comment by ritik0ranjan** [comment]
i think my setup files are creating some issues, i am sorry to disturb you. :\
