### ISSUE TITLE
Categories in Index page start from 2 instead of 1

### ISSUE THREAD

**Issue by anselal** [stroupbslayen/discord-pretty-help#34]
Is there a particular reason that the `Categories` index start from 2 ?
https://github.com/stroupbslayen/discord-pretty-help/blob/e41893354fed1f5d73c4b819864e93b9dcd9d3e0/pretty_help/pretty_help.py#L192

**Comment by CircuitSacul** [comment]
Because the index page is the first page, and it's showing the page number that the cogs are on

**Comment by stroupbslayen** [comment]
> 
> 
> Because the index page is the first page, and it's showing the page number that the cogs are on

This is correct. Closing this issue.

**Comment by CircuitSacul** [comment]
Perhaps this issue should be pinned
