### ISSUE TITLE
Add an author to the embed

### ISSUE THREAD

**Issue by anselal** [stroupbslayen/discord-pretty-help#36]
https://github.com/stroupbslayen/discord-pretty-help/blob/e41893354fed1f5d73c4b819864e93b9dcd9d3e0/pretty_help/pretty_help.py#L69

Hi there, it would be nice to add the author to the embed. What I was thinking was to modify the above line to something like this:

```python
return discord.Embed(title=title, description=description, color=self.color).set_author(
        name=f"{self.bot.name} Help",
        url="",
        icon_url=self.bot.user.avatar_url,
    )
```

the thing is that the Paginator class which holds the `_new_page` function does not include `self.bot`. I tried to add it but failed.

Is this something easy to implement ???

**Comment by stroupbslayen** [comment]
Hi, 

You would most do this with the `ending_note` param and reference `ctx.author.name`

```py
ending_note = "Help started by: {ctx.author.name}
bot.help_command = PrettyHelp(ending_note=ending_note)```

**Comment by anselal** [comment]
set_author sets this
![2021-04-16_23h00_47](https://user-images.githubusercontent.com/8732668/115078199-f04b8280-9f07-11eb-9cd7-385c7198908a.png)

but ending note is a footer

**Comment by stroupbslayen** [comment]
Ok I thought you wanted whoever input the help command to be mentioned in the help menu. The screenshot you posted seems a bit redundant to me since discord already shows who sent a message. Let me know if I'm still misunderstanding...

**Comment by anselal** [comment]
You understood it correctly. I just think it looks better.
