### ISSUE TITLE
Numbering starts from 2

### ISSUE THREAD

**Issue by luciferchase** [stroupbslayen/discord-pretty-help#39]
I checked in my bot and the gif in the README as well. In both, the numbering of the Cogs starts from 2 only.
Is this intentional or a known bug?

![image](https://user-images.githubusercontent.com/48217707/116998728-46883600-acfc-11eb-89e1-0aa5f384b1e6.png)

**Comment by CircuitSacul** [comment]
https://github.com/stroupbslayen/discord-pretty-help/issues/34
