### ISSUE TITLE
no module

### ISSUE THREAD

**Issue by FxcMike** [stroupbslayen/discord-pretty-help#4]
whats the pip install? No module names pretty_help

**Comment by stroupbslayen** [comment]
Currently there it's not on PyPi, it's on my list of things to do hopefully this week.

**Comment by FxcMike** [comment]
how do I use it then?

**Comment by stroupbslayen** [comment]
You would put he file in your project directory and import it like a normal python file.

**Comment by FxcMike** [comment]
Ok

**Comment by stroupbslayen** [comment]
it's been published and can be installed with `pip install discord-pretty-help`
