### ISSUE TITLE
Description not working

### ISSUE THREAD

**Issue by Shifulor** [stroupbslayen/discord-pretty-help#41]
Well, I suppose the tile says it all, when using cogs the description part doesn't work.
Oh and btw. the emoji also always gives errors.

**Comment by CircuitSacul** [comment]
Description works for me. Could you give me a reproducible example?

**Comment by stroupbslayen** [comment]
Yes, please provide your code or an example that produces the errors you're getting. There's not really much we can do to help with what you've given us.

**Comment by Shifulor** [comment]
**Main file:**


`import os
import discord
from dotenv import load_dotenv
from pretty_help import DefaultMenu, PrettyHelp

from discord.ext import commands, tasks

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')
GUILD = os.getenv('DISCORD_GUILD')
ID = os.getenv('GUILD')
menu = DefaultMenu(page_left="\U0001F44D", page_right="👎", remove=":discord:743511195197374563", active_time=5)

# Custom ending note
ending_note = "The ending note from {ctx.bot.user.name}\nFor command {help.clean_prefix}{help.invoked_with}"

bot = commands.Bot(command_prefix="<3")

bot.help_command = PrettyHelp(menu=menu, ending_note=ending_note)
initial_extensions = ['cogs.meme',
                      'cogs.tictactoe', 
                      'cogs.8ball', 
                      'cogs.dog',
                      'cogs.join',
                      'cogs.pause',
                      'cogs.resume',
                      'cogs.leave',
                      'cogs.avatar',
                      'cogs.roll_dice',
                      'cogs.ping',
                      'cogs.joined',
                      'cogs.kick',
                      'cogs.roles',
                      'cogs.say',
                      'cogs.ban',
                      'cogs.welcome']
if __name__ == '__main__':
    for extension in initial_extensions:
        bot.load_extension(extension)
@bot.event
async def on_ready():
      print('We have logged in')
guild = bot.get_guild(ID)


bot.run(TOKEN)`





**Cog:**
`import discord
import random
from discord.ext import commands, tasks
from pretty_help import DefaultMenu, PrettyHelp

response_list = ["As I see it, yes", "Yes", "No", "Very likely", "Not even close", "Maybe", "Very unlikely", "Gino's mom told me yes", "Gino's mom told me no", "Ask again later", "Better not tell you now", "Concentrate and ask again", "Don't count on it", " It is certain", "My sources say no", "Outlook good", "You may rely on it", "Very Doubtful", "Without a doubt"]



class ball8(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self._last_member = None

    @commands.command(aliases=['8ball'], description="awnsers a question")
    async def _8ball(self, ctx):
        await ctx.send(random.choice(response_list))
       
           



def setup(bot): 
    bot.add_cog(ball8(bot))`


**help command:**

<img width="240" alt="Screenshot 2021-05-22 at 00 45 01" src="https://user-images.githubusercontent.com/83807372/119204879-f4366b80-ba96-11eb-8887-b2d2543aa352.png">

**Comment by stroupbslayen** [comment]
Can you edit your post and put all of the code in a pastebin? Might be easier.

**Comment by Shifulor** [comment]
I will, bit im not home rn, so i only have my phone =) thanks in advance

**Comment by CircuitSacul** [comment]
To give a cog a description, do this:
```python
class MyCog(commands.Cog):
    "Cog description here"
    ...
```

Also, code blocks are done with 3 backticks before and after the code. See the screenshot below:
<img width="225" alt="Screen Shot 2021-05-21 at 8 16 37 PM" src="https://user-images.githubusercontent.com/55721663/119208721-73b14400-ba71-11eb-9bb6-70be23921352.png">

**Comment by Shifulor** [comment]
Thank  you very much, you guys are awesome, thanks :)
