### ISSUE TITLE
When the user gets help for a category without any commands an error gets raised.

### ISSUE THREAD

**Issue by thesadru** [stroupbslayen/discord-pretty-help#42]
Because commands that the user cannot run are automatically hidden some categories can have no available commands, this causes issues when trying to send a non-existent page.
```
Traceback (most recent call last):
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\help.py", line 853, in command_callback
    return await self.send_cog_help(cog)
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\pretty_help\pretty_help.py", line 354, in send_cog_help
    await self.send_pages()
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\pretty_help\pretty_help.py", line 297, in send_pages
    await self.menu.send_pages(self.context, destination, pages)
  File "C:\Users\D\AppData\Roaming\Python\Python39\site-packages\pretty_help\menu.py", line 103, in send_pages
    message: discord.Message = await destination.send(embed=pages[0])
IndexError: list index out of range
```
If the pages are empty the bot should just return without sending anything like it currently does for unavailable commands.

**Comment by CircuitSacul** [comment]
Could you give a reproducible example?

**Comment by thesadru** [comment]
```py
from discord.ext import commands
from pretty_help import PrettyHelp

bot = commands.Bot('!',help_command=PrettyHelp())

class category(commands.Cog):
    @commands.command()
    @commands.dm_only()
    async def command(self, ctx):
        await ctx.send('hi')

bot.add_cog(category())
```
when the command is ran in a guild both `!help` and `!help command` work as expected, but `!help category` fails

**Comment by CircuitSacul** [comment]
@stroupbslayen I was able to reproduce this error. If I find time later I might make a pr to fix it

**Comment by stroupbslayen** [comment]
The way the default discord.py help menu handles these is to just send the footer, I guess we could do the same thing here. It's an easy fix. Thoughts?

**Comment by CircuitSacul** [comment]
I mean it might make more sense to hide commands users can't run from bot_help/cog_help/group_help, but if they explicitly ask for help with the hidden command still send it.

So like:
!help  # doesn't show hidden command
!help Cog  # doesn't show hidden command
!help group  # still doesn't show hidden command
!help group hidden_command  # shows help

**Comment by CircuitSacul** [comment]
This might be better as an option though

**Comment by stroupbslayen** [comment]
> 
> 
> I mean it might make more sense to hide commands users can't run from bot_help/cog_help/group_help, but if they explicitly ask for help with the hidden command still send it.
> 
> So like:
> !help # doesn't show hidden command
> !help Cog # doesn't show hidden command
> !help group # still doesn't show hidden command
> !help group hidden_command # shows help

I disagree with this, generally commands are put behind walls for a reason.

**Comment by stroupbslayen** [comment]
Updated so the bot will just respond with the footer in this situation.
