### ISSUE TITLE
[Feature Request] Clean up after timeout

### ISSUE THREAD

**Issue by tylovejoy** [stroupbslayen/discord-pretty-help#44]
It would be great if there was a "delete help message" after timeout. Pretty much how the remove button works, but as soon as the reactions get deleted, just delete the message instead.

**Comment by stroupbslayen** [comment]
Sure, I this could be worked in.

**Comment by stroupbslayen** [comment]
Added `delete_after_timeout` to 1.3.3. Thanks for the suggestion.
