### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Slurpcy** [stroupbslayen/discord-pretty-help#45]
it states no module found, and fails to download using pip cmd , it says invalid distribution of packages i use ``pip install discord-pretty-help``

**Comment by CircuitSacul** [comment]
Could you check the version of pip/python with `pip --version`

**Comment by Lime007** [comment]
its ``21.1.2``

**Comment by Lime007** [comment]
python is ``3.8.9``

**Comment by Lime007** [comment]
![Capture](https://user-images.githubusercontent.com/75667833/123306185-05f5ad80-d532-11eb-891b-5f9b90a9138e.PNG)
error

**Comment by CircuitSacul** [comment]
Looks more like a warning? It says discord-pretty-help is already installed

**Comment by Lime007** [comment]
But when I run the bot it says pretty_help named no module was found

**Comment by Lime007** [comment]
Any idea how can I use it ?

**Comment by stroupbslayen** [comment]
Try creating a venv and using it there?
