### ISSUE TITLE
[Feature Request] Ignore command/cog

### ISSUE THREAD

**Issue by Toricane** [stroupbslayen/discord-pretty-help#46]
I have commands and cogs that I don't want to be displayed on the help command pages, it would be great if there was a way to ignore specific command/cog names.

**Comment by stroupbslayen** [comment]
I would suggest using [checks ](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#checks) to do this. The help command does not show commands that message sender isn't approved for.

**Comment by CircuitSacul** [comment]
What if you’ve set `verify_checks=False` but you still want to hide certain cogs?

**Comment by stroupbslayen** [comment]
Then I guess you shouldn't set `verify_checks=False` ?

**Comment by Toricane** [comment]
How do I use checks with the PrettyHelp class inside the `commands.Bot(help_command=PrettyHelp())`?

**Comment by stroupbslayen** [comment]
You don't, you use them on your commands as shown in the examples.

**Comment by Toricane** [comment]
Okay, thanks!
