### ISSUE TITLE
Custom "No command called "foo" found"

### ISSUE THREAD

**Issue by PlasmaAsDev** [stroupbslayen/discord-pretty-help#47]
Well, i think the title explains a lot, but would be nice if you can implement because i want to translate the help command and i have to mess with the entire `discord.ext` class :(

![image](https://user-images.githubusercontent.com/56369290/125374211-ee555c00-e35c-11eb-9bfc-29b92d4a1a50.png)

**Comment by CircuitSacul** [comment]
I would suggest subclassing the errors classes so you can translate them.

**Comment by stroupbslayen** [comment]
If you want to change the output you can subclass `PrettyHelp`:

```py
class NotFound(PrettyHelp):
    def command_not_found(self, string: str) -> str:
        return f"I can't find anything for **{string}**"

bot = commands.Bot(help=NotFound()
```

![image](https://user-images.githubusercontent.com/29642143/185808517-bbebbce1-8683-4ac7-a354-125b3b66b78b.png)
