### ISSUE TITLE
2 menus appear instead of one

### ISSUE THREAD

**Issue by shadawcraw** [stroupbslayen/discord-pretty-help#48]
I don't know if this is intentional, but the bot sends 2 embeds instead of one.
My client.help_command: `client.help_command = PrettyHelp(ending_note="George Floyd Gaming", show_index=False, no_category="Misc")`

**Comment by stroupbslayen** [comment]
Generally that means you have two instances of your bot running.

**Comment by shadawcraw** [comment]
Apparantly it fixed itself after a bit. Thanks for responding!
