### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by RaymondLWong** [stroupbslayen/discord-pretty-help#50]
Allow command groups (`@bot.group()`) to be a category (just like cogs). I have a lot of command groups that have subcommands, but they're sort of hidden, as it's only one entry in the No Category section. It would be nice if I had a dedicated page for that command group and subcommands, similar to cogs, so that all the commands are more visible. I'm sure others also use command groups similarly, so it would be a useful feature.

Example:
```
@bot.group()
async def shop(context: Context):
    pass
    
@shop.command()
async def shop_a_name(context: Context):
    pass
    
@shop.command()
async def shop_b_name(context: Context):
    pass
```

**Comment by stroupbslayen** [comment]
You would do `!help <group_command_name>` to see that sheet.

**Comment by RaymondLWong** [comment]
I know, but perhaps I wasn't clear. I was referring to the default view when you type `!help` and you change pages. Cogs and their seem to have their own pages but not command groups.

**Comment by stroupbslayen** [comment]
Correct. The default `help` is just for representing cogs as pages. Command groups are treated as normal commands in their representation. I understand what you're saying, but commands groups can also contain other command groups and now you have issues with recursively adding X number of pages depending on how deep someone goes with group commands. If you'd like to make your users more aware that your command is a group command, I suggest making note of it in your command description 🙂 Thank you for the suggestion though!
