### ISSUE TITLE
ImportError: cannot import name 'Navigation' from 'pretty_help'

### ISSUE THREAD

**Issue by AgentLoneStar007** [stroupbslayen/discord-pretty-help#52]
I recently started using this library for a Discord bot I'm making. I went to start the bot, and it says it can't import Navigation from pretty help.
![image](https://user-images.githubusercontent.com/57960152/127229291-bc49d74b-620e-4aa8-85ab-10d47dc8ff41.png)
Was this deprecated without my knowing, or am I doing something wrong?

**Comment by stroupbslayen** [comment]
Yes, this was depreciated and replaced with `DefaultMenu` See the revised README for an example. This was done so others could create custom menus and integrate them more easily. Sorry for the inconvenience.

**Comment by AgentLoneStar007** [comment]
Thanks for the help.
