### ISSUE TITLE
Minor typo in test

### ISSUE THREAD

**Issue by anselal** [stroupbslayen/discord-pretty-help#55]
https://github.com/stroupbslayen/discord-pretty-help/blob/1c824527ae404f4721e7b07ba2b1b68a03a52a77/tests/test_discord_pretty_help.py#L20

I think it should be `show_index=False`.

I don't create a PR was this. You can fix it in the next release since it is commented out

**Comment by stroupbslayen** [comment]
Fixed, thank you.
