### ISSUE TITLE
How can I remove cogs from being shown.

### ISSUE THREAD

**Issue by CoderN-P** [stroupbslayen/discord-pretty-help#57]
For example, let's say I have some cogs that I do not want to be on the help command, how would I go on removing the cog from the help command?

**Comment by stroupbslayen** [comment]
I would just add a cog check to not show it. 

[cog_check reference](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Cog.cog_check)

```py
    async def cog_check(self, ctx: commands.Context):
        if ctx.invoked_with != "help":
            return True
```

**Comment by CoderN-P** [comment]
Gret! I will try this out.
