### ISSUE TITLE
Respect "hidden" 

### ISSUE THREAD

**Issue by Rxann** [stroupbslayen/discord-pretty-help#59]
I would really appreciate it if the help commands would respect the hidden kwarg for commands.comand() or client.command()

This would give us the ability to make use of the hidden option

**Comment by stroupbslayen** [comment]
Are you sure you're using it the `hidden` kwarg correctly? I was pretty sure it already does this and a quick test confirmed it on my end. The snippet below outputs the what you would expect.

```py
@bot.command(hidden=True)
async def hidden(ctx: commands.Context):
    await ctx.send("This is hidden")


@bot.command()
async def test(ctx: commands.Context):
    await ctx.send("this is the test command")
```

![image](https://user-images.githubusercontent.com/29642143/130330241-27ba1332-41e8-4ed2-9034-ef59e7e3f16b.png)

**Comment by Rxann** [comment]
I will do this and comment if it works or not! Thanks for the help
