### ISSUE TITLE
Unable to find 'discord.ext.commands.help' when using a fork of discord.py

### ISSUE THREAD

**Issue by squigjess** [stroupbslayen/discord-pretty-help#63]
My project currently uses Nextcord, a fork of discord.py that works as a drop-in replacement for discord.py.

When importing and invoking `discord-pretty-help` ​like below...
```
import nextcord as discord
from nextcord.ext import commands
from pretty_help import PrettyHelp
...
client = commands.Bot(command_prefix=commands.command_prefix(config.COMMAND_PREFIX), help_command=PrettyHelp())
```

...Python throws a `ModuleNotFoundError`, with the reason `No module named 'discord.ext.commands.help'`. Full traceback is at the bottom of this issue.

Given that  `discord-pretty-help` claims to (probably) support forks of `discord.py` on the [PyPi page](https://pypi.org/project/discord-pretty-help/), I'm wondering if this is a bug or if I may have forgotten something.

Happy to help troubleshoot as needed!

---------------

```
Traceback (most recent call last):
  File "PROJECTDIRECTORY/bot.py", line 8, in <module>
    from pretty_help import PrettyHelp
  File "PROJECTDIRECTORY/venv/lib/python3.9/site-packages/pretty_help/__init__.py", line 2, in <module>
    from .pretty_help import *
  File "PROJECTDIRECTORY/venv/lib/python3.9/site-packages/pretty_help/pretty_help.py", line 9, in <module>
    from discord.ext.commands.help import HelpCommand
ModuleNotFoundError: No module named 'discord.ext.commands.help'
```

**Comment by stroupbslayen** [comment]
Thanks for bringing this up. The error indicates a blatant oversight on my end, obviously `discord` is not installed when you're running `nextcord` or any other fork most likely so the import fails. You might be able to get away with installing discord.py in your project as until I can fix this.
