### ISSUE TITLE
Command raised an exception: AttributeError: 'PrettyHelp' object has no attribute 'clean_prefix'

### ISSUE THREAD

**Issue by KeparYTbcc** [stroupbslayen/discord-pretty-help#69]
Command raised an exception: AttributeError: 'PrettyHelp' object has no attribute 'clean_prefix'

**Comment by KeparYTbcc** [comment]
```
import discord
from discord.ext import commands
from pretty_help import PrettyHelp

intents = discord.Intents.default()  
intents.message_content = True

bot = commands.Bot(command_prefix = '?', intents = intents, help_command=PrettyHelp())
```

**Comment by stroupbslayen** [comment]
If you're using discord.py v2, this has not been tested with that. I'm waiting for the full release before diving in and updating this.

**Comment by PhazonJim** [comment]
+1 on this being an issue in discord.py v2

**Comment by regulad** [comment]
@stroupbslayen My PR fixed this issue, but it didn't automatically close.
