### ISSUE TITLE
How to make a description

### ISSUE THREAD

**Issue by BaguetteSan** [stroupbslayen/discord-pretty-help#75]
I have the brief, description, and name in the command/cog, but it wont show up. The command works find and when I do help (command) it shows the description but not in !help 
![image](https://user-images.githubusercontent.com/81198502/167326658-6fdafb63-4fb9-4df1-9589-b1facff8f1fd.png)
![image](https://user-images.githubusercontent.com/81198502/167326717-f23369fc-e715-4c0d-bc25-2b76dc558bfe.png)

**Comment by Regeents** [comment]
It not appear because you write description for your command and your image shows the "Categories". If your want to add description for you categoires you should edit your class. 

Example:

``` python 
class Ping(commands.Cog, name='Category Name', description='Category Description'):
    def __init__(self, client):
        self.client = client
```

**Comment by stroupbslayen** [comment]
> It not appear because you write description for your command and your image shows the "Categories". If you want to add description for your categories you should edit your class.

This is correct, add a description to your cog for it to show up in the menu.
