### ISSUE TITLE
Support slash commands

### ISSUE THREAD

**Issue by erincerys** [stroupbslayen/discord-pretty-help#80]
When a cog contains slash commands, or a slash command is loaded directly into the bot, they aren't displayed in the categories, or uncategorized section.

Are you working on implementing this functionality, or should I consider a different library/rolling my own? :/

**Comment by erincerys** [comment]
It would appear that you are indeed, on the `v2` branch, but it doesn't work.

When I try to start the bot, I get this exception:

```
Traceback (most recent call last):
...
  File "./cables/cabling_bot/main.py", line 5, in <module>
    from pretty_help import DefaultMenu, PrettyHelp
  File "/home/erin/.cache/pypoetry/virtualenvs/cabling-bot-417_n4la-py3.10/lib/python3.10/site-packages/pretty_help/__init__.py", line 2, in <module>
    from .pretty_help import *
  File "/home/erin/.cache/pypoetry/virtualenvs/cabling-bot-417_n4la-py3.10/lib/python3.10/site-packages/pretty_help/pretty_help.py", line 7, in <module>
    from discord import app_commands
ImportError: cannot import name 'app_commands' from 'discord' (/home/erin/.cache/pypoetry/virtualenvs/cabling-bot-417_n4la-py3.10/lib/python3.10/site-packages/discord/__init__.py)
```

My framework is `py-cord` at a recent commit on `master`.

**Comment by stroupbslayen** [comment]
Yes, the v2 branch will support slash commands, however it will only support `discord.py` as I don't use or follow changes from other forks. It appears `py-cord` implements the slash command api differently than `discord.py` and that's why you're getting the error.
