### ISSUE TITLE
Command "help" is not found

### ISSUE THREAD

**Issue by Niko621** [stroupbslayen/discord-pretty-help#83]
![image](https://user-images.githubusercontent.com/118218123/204062075-976c317b-dff0-4a82-b5cd-caef4e61a1e4.png)
![image](https://user-images.githubusercontent.com/118218123/204062162-a55d81ae-9960-444f-af6b-26a0e17971c5.png)

For some reason the help command isn't being registered/can't be found or isn't an existing command. Can you tell me what the problem is?

**Comment by stroupbslayen** [comment]
are you deleting the help command somewhere else in your bot? Something like `bot.remove_command("help")` in another cog or something? That's the only thing I can think of at the moment.

**Comment by Niko621** [comment]
Yeah that was the problem, somewhere in my code was a line that removed the help command, thanks for the help!
