### ISSUE TITLE
No Category

### ISSUE THREAD

**Issue by zefanjajobse** [stroupbslayen/discord-pretty-help#9]
the no category shows only the help command, 
is there a way to remove the no category page?
![image](https://user-images.githubusercontent.com/22680656/92301899-bf65a100-ef67-11ea-81f4-ec09a8af4899.png)

**Comment by stroupbslayen** [comment]
Sure, there are a few other changes that have been suggested this week so I'll look into incorporating this in there as well. Thanks for your input.

**Comment by stroupbslayen** [comment]
Latest version should address your issue.
