### ISSUE TITLE
doesnt work with py-cord

### ISSUE THREAD

**Issue by KraoESPfan1n** [stroupbslayen/discord-pretty-help#95]
Exception has occurred: ImportError
cannot import name 'app_commands' from 'discord' (C:\Users\Angel\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\__init__.py)
  File "C:\Users\user\Downloads\yonny\main.py", line 24, in <module>
    from pretty_help import PrettyHelp
ImportError: cannot import name 'app_commands' from 'discord' (C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\__init__.py)
![image](https://github.com/CasuallyCalm/discord-pretty-help/assets/136997481/94c9744f-471c-4fe2-b947-2be3f1b19dd2)

**Comment by CasuallyCalm** [comment]
Use discord.py
